name: Deploy React App Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t akashjdongre/react-app-img-dev:latest -f dockerfile.dev .

      - name: Push Docker image
        run: docker push akashjdongre/react-app-img-dev:latest

      - name: Create Dockerrun file
        run: |
          cat > Dockerrun.aws.json << 'EOF'
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "akashjdongre/react-app-img-dev:latest",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "80"
              }
            ]
          }
          EOF

      - name: Debug Dockerrun
        run: cat Dockerrun.aws.json

      - name: Zip deployment package
        run: zip deploy.zip Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: "react frontent"
          environment_name: Reactfrontent-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-994878981390
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}